# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: OtherMonad

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
        
    - name: SonarCloud Scan
      run: |
        dotnet tool install --global dotnet-sonarscanner --version 5.2.0
        dotnet tool update dotnet-reportgenerator-globaltool -g --version 4.8.7
        dotnet sonarscanner begin /k:"piqueterron_OtherMonad" /o:"piqueterron" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.verbose="true" /d:sonar.coverageReportPaths=".\sonarqubecoverage\SonarQube.xml"
        dotnet build
        dotnet test --no-build --collect:"XPlat Code Coverage"
        reportgenerator "-reports:*\TestResults\*\coverage.cobertura.xml" "-targetdir:sonarqubecoverage" "-reporttypes:SonarQube"
        dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
